2019-04-01 20:50:02,294 ERROR: Exception on /reset_password_request [POST] [in c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Linford Hao\microblog\app\routes.py", line 211, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Linford Hao\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token),
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\linfor~1\virtua~1\linfor~1\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2019-04-01 20:52:56,813 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:71]
2019-04-01 20:55:02,462 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:71]
2019-04-01 21:03:21,166 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:71]
2019-04-01 21:42:27,456 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:73]
2019-04-01 21:46:03,637 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:73]
2019-04-02 15:39:49,333 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:73]
2019-04-02 16:18:00,955 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:75]
2019-04-02 16:21:37,123 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:75]
2019-04-07 18:52:51,873 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:84]
2019-04-07 18:54:02,455 INFO: Microblog startup [in C:\Users\Linford Hao\microblog\app\__init__.py:84]
